{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user{{ $attendee }}-registry
  namespace: rhoai-model-registries
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-user-user{{ $attendee }}-registry
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-permissions-user{{ $attendee }}-registry
  namespace: rhoai-model-registries
  labels:
    app: user{{ $attendee }}-registry
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/name: user{{ $attendee }}-registry
    app.kubernetes.io/part-of: model-registry
    component: model-registry
    opendatahub.io/dashboard: 'true'
    opendatahub.io/rb-project-subject: 'true'
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:user{{ $attendee }}-jukebox'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-user-user{{ $attendee }}-registry
{{- end }}