{{ $cluster_domain := .Values.cluster_domain }}
{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: Secret
apiVersion: v1
metadata:
  name: mlops-gitops-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee}}/mlops-gitops.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: mlops-helmcharts-repo-secret
  namespace: user{{ $attendee}}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/mlops-helmcharts.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: jukebox-ui-repo-secret
  namespace: user{{ $attendee}}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/jukebox-ui.git
  username: user{{ $attendee }}
type: Opaque
{{- end }}
