{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-rhacs-tokens
  namespace: user{{ $attendee }}-toolings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-rhacs-tokens-rb
  namespace: user{{ $attendee }}-toolings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: create-rhacs-tokens
  namespace: user{{ $attendee }}-toolings
{{- end }}
