---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-rhacs-tokens
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - patch
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - get
      - list
---
{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-rhacs-tokens
  namespace: user{{ $attendee }}-toolings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-rhacs-tokens-rb
  namespace: user{{ $attendee }}-toolings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: create-rhacs-tokens
  namespace: user{{ $attendee }}-toolings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-rhacs-tokens-user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-rhacs-tokens
subjects:
- kind: ServiceAccount
  name: create-rhacs-tokens
  namespace: user{{ $attendee }}-toolings
{{- end }}
