apiVersion: v2
name: ml500-base
description: A Helm chart to deploy the ML500 Lab 
type: application
version: 1.0.0
appVersion: 1.0.0 
maintainers:
  - name: rcarrata
  - name: nstrung
  - name: rhrolun
  - name: ckavili
