apiVersion: v2
name: ai500-operators
description: A Helm chart to deploy the AI500 Toolings 
type: application
version: 1.0.0
appVersion: 1.0.0 
maintainers:
  - name: rcarrata
  - name: nstrung
  - name: rhrolun
  - name: ckavili
