FROM quay.io/modh/codeserver:codeserver-ubi9-python-3.9-20240829-6be50fc

WORKDIR /opt/app-root/bin

USER root

# enablement stuff
ENV ARGOCD_VERSION=2.7.1 \
    YQ_VERSION=4.44.3 \
    HELM_VERSION=3.15.4 \
    # KUBESEAL_VERSION=0.20.5 \
    TEKTON_VERSION=1.11.0 \
    JQ_VERSION=1.7.1 \
    # CONFTEST_VERSION=0.41.0 \
    # ROX_VERSION=3.74.3 \
    # KUBELINTER_VERSION=0.6.3 \
    # COSIGN_VERSION=2.2.3 \
    # K6_VERSION=0.44.0 \
    # JSONNET_VERSION=0.20.0 \
    SYFT_VERSION=0.82.0

# tekton
RUN curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/${TEKTON_VERSION}/tkn-linux-amd64.tar.gz | tar --no-same-owner -xzf - -C /usr/local/bin tkn && \
chmod -R 755 /usr/local/bin/tkn 

# jq / yq
RUN curl -sLo /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 && \
    chmod +x /usr/local/bin/jq && \
    curl -sLo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64 && \
    chmod +x /usr/local/bin/yq

# helm
RUN curl -skL -o /tmp/helm.tar.gz https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz && \
tar -C /tmp -xzf /tmp/helm.tar.gz && \
mv -v /tmp/linux-amd64/helm /usr/local/bin && \
chmod -R 775 /usr/local/bin/helm && \
rm -rf /tmp/linux-amd64 
 
COPY scripts/startup.sh /opt/app-root/bin/startup.sh

RUN chmod a+x /opt/app-root/bin/startup.sh

# sort out git
RUN echo "git config --global http.sslVerify false" | tee -a /etc/bashrc && \
    echo "git config --global user.name 'MLOps Wizard'" | tee -a /etc/bashrc&& \
    echo "git config --global user.email 'mlops@wizard.com'" | tee -a /etc/bashrc && \
    echo "git config --global credential.helper 'cache --timeout=172800'" | tee -a /etc/bashrc && \
    echo "git config --global pull.rebase 'false'" | tee -a /etc/bashrc && \
    echo "git config --global push.default 'simple'" | tee -a /etc/bashrc && \

USER 1001

ENTRYPOINT [ "startup.sh" ]
