{{ $attendees := (.Values.attendees | int) }}
{{- range $attendee := until $attendees }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: user{{ $attendee }}-jukebox
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
{{- end }}